# Generated by Django 5.2.3 on 2025-06-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=20, verbose_name='Остаток(шт.)'),
        ),
    ]
